version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: React_Container
    # environment:
    #   - WDS_SOCKET_PORT=0
    expose:
      - "3000:3000"
    ports:
      # - "12345:3000"
      - "3000:3000"