services:

  backend:
    image: backend
    build:
      context: backend
      dockerfile: ../backend/Dockerfile
    restart: always
    expose:
      - "8080"
    # networks:
      # - react-spring

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ../frontend/Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    restart: always
    # expose:
      # - "3000"
    # networks:
    #   - react-spring
    ports:
      - "12345:3000"
      # - "3000:3000"
    depends_on:
      - backend

# networks:
#   react-spring:
#     driver: bridge

# Tried to add proxy
  # proxy:
  #   image: nginx:1.17
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

  nginx-proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
