version: '3'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    container_name: Springboot_Server
    expose:
      - "8080:8080"
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
    networks:
      - react-spring

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    container_name: React
    environment:
      - WDS_SOCKET_PORT=0
    # expose:
      # - "3000"
    networks:
      - react-spring
    ports:
      # - "12345:3000"
      - "3000:3000"
    depends_on:
      - backend

networks:
  react-spring:

# Tried to add proxy
  # proxy:
  #   image: nginx:1.17
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

  # nginx-proxy:
  #   image: nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend
