// package com.cursed.bjs.controllers;

// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.stereotype.Controller;
// import org.springframework.web.bind.annotation.GetMapping;
// import org.springframework.web.bind.annotation.PostMapping;
// import org.springframework.web.bind.annotation.RequestMapping;
// import org.springframework.web.bind.annotation.RequestParam;
// import org.springframework.web.bind.annotation.ResponseBody;

// import com.cursed.bjs.database.User;
// import com.cursed.bjs.database.UserRepository;

// @Controller // This means that this class is a Controller
// @RequestMapping("/api/v1/database") // This means URL's start with /demo (after Application path)
// public class DatabaseController {
//   @Autowired // This means to get the bean called userRepository
//          // Which is auto-generated by Spring, we will use it to handle the data
//   private UserRepository userRepository;

//   @PostMapping("/add") // Map ONLY POST Requests
//   public @ResponseBody String addNewUser (@RequestParam String name
//       , @RequestParam String email) {
//     // @ResponseBody means the returned String is the response, not a view name
//     // @RequestParam means it is a parameter from the GET or POST request

//     User n = new User();
//     n.setName(name);
//     n.setEmail(email);
//     userRepository.save(n);
//     return "Saved";
//   }

//   @GetMapping("/all")
//   public @ResponseBody Iterable<User> getAllUsers() {
//     // This returns a JSON or XML with the users
//     return userRepository.findAll();
//   }
// }
