name: Push Docker Backend Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Get Repo
      uses: actions/checkout@v3

    - name: Go to the backend folder
      run: cd backend
      
    - name: Build and Push
      env: 
        $SECRET: ${{ secrets.WOLOLOLO }}
      run: |
        touch file
        echo $SECRET >> file

    - name: Check file
      run: cat file

    - name: Get version
      id: vars
      run: echo "version=$(cat file)" >> $GITHUB_OUTPUT
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}
