# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Get Repo
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Change directory and install dependencies	
      working-directory: frontend	
      run: |
        npm ci

    - name: Build	
      working-directory: frontend	
      run: |
        npm run build --if-present

    # Did not make any tests so lets assume for now that if its compiles with warnings then its ok
    #- name: Run tests	
    #  working-directory: frontend	
    #  run: |
    #    npm test
